#:schema node_modules/wrangler/config-schema.json
name = "better-rammerhead"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
routes = [
  { pattern = "*.schmaa.com/static/css/main*", zone_name = "schmaa.com" }
  { pattern = "*.schmaa.com/static/js/main*", zone_name = "schmaa.com" }
]

[observability]
enabled = true

[placement]
mode = "smart"
